// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cohxuwftnakcjlqpsbil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaHh1d2Z0bmFrY2pscXBzYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODU5NDAsImV4cCI6MjA2MTg2MTk0MH0.a-jgIvNxbIFae6rxWPffEMdhx-yh5Je0Im9F11LGxPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);